import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Open_Sans, Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Zavifoft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${openSans.variable}`}>
        <div className="mx-auto w-full max-w-[1440px] px-4 lg:px-[60px]">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
